name: Lint, Test, Deploy 
on: workflow_dispatch
jobs:
  test_lint_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run lint
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploy"